FROM node:16 as builder

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY src src
COPY rollup.config.js rollup.config.js
COPY tsconfig.json tsconfig.json

CMD npm run watch

EXPOSE 3001
