version: '3.7'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npx nodemon src/server.ts
    volumes:
      - ./backend/src:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
      - ./frontend/src:/app/src
  proxy:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 3000:80
    command: nginx -g 'daemon off;'
    depends_on:
      - server
      - frontend
