version: '3.7'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npx nodemon src/server.ts
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sheet-creator
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
      - ./frontend/src:/app/src
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sheet-creator
    volumes:
      - postgres:/var/lib/postgresql/data
  proxy:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 3000:80
    command: nginx -g 'daemon off;'
    depends_on:
      - server
      - frontend
volumes:
  postgres:
